### ISSUE TITLE
Remove event listener after a certain time?

### ISSUE THREAD

**Issue by atwj** [primus/eventemitter3#101]
Hey! I was wondering if there was anyway currently to remove an eventListener after a certain period of time. The use case could be where I've set a user's ID as an event name `event.on(user_id, doSmth())` and Im waiting on the user to reply me, on which I will emit the ID. However if the user does not reply after a certain duration say 30mins, the eventListener will be removed

**Comment by lpinca** [comment]
I'd use a timer that upon expiration remove the listener.

```js
function doSmth() {}

ee.on(user_id, doSmth);

setTimeout(function () {
  ee.removeListener(user_id, doSmth)
}, 30 * 60 * 1000);
```
