### ISSUE TITLE
import emitter by typescript throw error

### ISSUE THREAD

**Issue by allex** [primus/eventemitter3#182]
failed when used in typescript project:

```js
import {EventEmitter} from 'events';
````

throws

```
{ Error: 'EventEmitter' is not exported by node_modules/eventemitter3/index.js
```

could you please add `pkg.module` section for esm module ecosystem.

**Comment by GrosSacASac** [comment]
Could you try with this one https://www.npmjs.com/package/event-e3

**Comment by cedx** [comment]
On my side, no problem to use with TypeScript.
There's a typo in the code sample:

```ts
import {EventEmitter} from 'eventemitter3';
```

**Comment by lpinca** [comment]
Closing as per @cedx comment.

**Comment by dtassone** [comment]
`import * as events from 'events';` works.
