### ISSUE TITLE
This is not an alternative to eventemitter2

### ISSUE THREAD

**Issue by fresheneesz** [primus/eventemitter3#19]
Your readme suggests that this is an alternative to eventemitter2, but it sounds like you aren't implementing any extended features at all. In fact, this has less features than node's EventEmitter by design. So please remove the part about this being at all related to eventemitter2.

**Comment by 3rd-Eden** [comment]
It states that it's a faster alternative then EE2 as the creators of EE2 often stated that it's the fastest event emitter..
