### ISSUE TITLE
Add to bower

### ISSUE THREAD

**Issue by goatslacker** [primus/eventemitter3#20]
Would you accept a PR?

**Comment by lpinca** [comment]
I think that it is fine, but wait for a response from @3rd-Eden (he is bit busy these days).

**Comment by 3rd-Eden** [comment]
Yes, ill accept pull requests for it but I won't be maintaining it.

Arnout Kazemier

**Comment by goatslacker** [comment]
That's fine, EventEmitter3 doesn't really seem to change. PR coming up.
