### ISSUE TITLE
Rate exceeded.

### ISSUE THREAD

**Issue by wangxingxing123654** [primus/eventemitter3#210]
![image](https://user-images.githubusercontent.com/28847126/71400212-fce7ff80-2660-11ea-990c-9f1f9bf0d4b0.png)

**Comment by wangxingxing123654** [comment]
Events is not a constructor???? change another cdn there is a something wrong again

**Comment by 3rd-Eden** [comment]
Rate exceeded sounds like a response from unpkg, instead of EventEmitter it self. Instead of relying on external CDN's I would suggest just bundling the code with your project.
