### ISSUE TITLE
evt listener count judgement by `handlers.fn` may got wrong results

### ISSUE THREAD

**Issue by SunGuoQiang123** [primus/eventemitter3#214]
if someone makes some changes like  `Array.prototype.fn = function() {}`  , then the judgement for the event listener count may get wrong results when the event have more than one listeners 

```javascript
Array.prototype.fn = function() {};
const em = new EventEmitter();
em.on('test', a => a);
em.on('test', a => console.log(a));
console.log(em.listenerCount('test'));
```

not sure if this is necessary because this is very rare to happen, if so, just close this issue

**Comment by lpinca** [comment]
Yes, I don't think this is a problem. Changing the prototype if standard, built-in objects, is not common and recommended.
