### ISSUE TITLE
Type errors when wrapping emit in a function passing all args

### ISSUE THREAD

**Issue by marcelbeumer** [primus/eventemitter3#218]
How to achieve the following with EventEmitter? Thanks!

```ts
import EventEmitter from 'eventemitter3';

export interface Events {
  start: [{}];
  stop: [{}];
  error: [{ error: Error }];
}

function addLogging<T extends (...args: any[]) => any>(
  fn: T
): (...args: Parameters<T>) => ReturnType<T> {
  return (...args) => {
    console.log('Add some logging');
    return fn(...args);
  };
}

const otherFn = (a: number, b: number) => a * b;
const otherFnLogged = addLogging(otherFn);
const eventEmitter = new EventEmitter<Events>();
const emitLogged = addLogging(eventEmitter.emit);

otherFnLogged(1, 2); // fine
otherFnLogged(1, 2); // fine
eventEmitter.emit('start', {}); // fine
emitLogged('start', {}); // <-- error because TS says its (...args: never) => boolean
```

**Comment by lpinca** [comment]
I don't know, I don't use TypeScript.

**Comment by namnm** [comment]
@marcelbeumer Because `emit` itself is a generic function, when you call `addLogging(eventEmitter.emit);` you have stripped out the generic part, thus `args` become never.

You can define another function `addLoggingEmit`, which redefine the generic signature:
```ts
type Func = (...args: any[]) => any;
type GenericEmit<T extends EventEmitter.ValidEventTypes> =
  <K extends EventEmitter.EventNames<T>>(e: K, ...args: EventEmitter.EventArgs<T, K>) => boolean;
function addLoggingEmit<T extends EventEmitter.ValidEventTypes>(fn: Func): GenericEmit<T> {
  return addLogging(fn);
}

const emitLogged = addLoggingEmit(eventEmitter.emit);
emitLogged('start', {}); // fine
```

**Comment by ljporljp** [comment]
no easy code，no good design。

**Comment by unional** [comment]
[playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAUQG4FMB2MEmDGKpwBmUEIcA5CqhitrvgMzkDcAsAFAcoAekscwGlEIBDAMYpE1GAGc4Abw5w4MmCNgAuOAG15AXwC6bdstUQwW3YePL8JKJflw70LQij241jno4dCAK5oYjDAEGhwIgAmUQAyEADmCYIJADwAKs7ceGhRcgAUAHTF6gkyWiJoAJ7aBgCUcAC8AHyR1c35SkRoWukcdVpFJVBlWgAK6iIgKHhQMhnNDS1wAEozAVBo6VVgKAsKXVDrm3BDhaUyS62KJspwYuEyEAA2KIXPifnkAIIxKqSSD5JFLkOo2O5HGAbCKENBnC5grp6Yy+TjsB5oVRwCAwAAW+AAYhFGqcRFo0AEQAAjfAAGjgVPJlJpUCukTgACoGcYMVicfioET4kkUFEmpEYsLkmgEvl+YS0Ij0Y94FR0Jg6LNxWgUAB3KTqrA4WapZDqmQdJW81V0KWi8XROKJaWytUYI30KCFWg4JUceWCtB2qL5ACM9IATGC4AB6GNEQQof14hXBsOR6NxhM6rjSD2zb10L6qdQwcj0-SZ+OERNcW3O0XFtSwcsKPRVuCpAC0XecHmgDJQYhEARkknSAGUVCIqnIcAViucRuU4DrUKymq0qRAXihKkA)


I guess this is not an issue anymore?

**Comment by lpinca** [comment]
I'm closing this as per @unional's comment. Please comment if this needs to stay open.
