### ISSUE TITLE
PR into node

### ISSUE THREAD

**Issue by nkt** [primus/eventemitter3#23]
Are you going to send patch into node/io.js?

**Comment by Dashed** [comment]
@nkt eventemitter3 isn't going to replace EventEmitter within node/io.js.eventemitter3 is meant to be optimized for browsers.

**Comment by nkt** [comment]
Ah. I understood. thanks.

**Comment by 3rd-Eden** [comment]
@Dashed @nkt The performance fixes aren't browser only, as we actually benchmark against the Node.js implementation. And getting the performance patches up stream has proven to be really painful for node as they don't like it when people touch the EventEmitter. They are also fundamentally against API changes to major performance benefits such as our `EE.on(event, fn, context)` are not accepted even if they proof a major performance win.
