### ISSUE TITLE
Support for ESMoudle

### ISSUE THREAD

**Issue by sixiakun** [primus/eventemitter3#235]
I’m using snowpack, it depend on esm.
I have a dependency which use eventemitter3.
Thanks for open source.
And is this a plan for esm?

**Comment by sixiakun** [comment]
sorry,i think i can reslove it by myself

**Comment by tillsanders** [comment]
I created a native ESM-version of EventEmitter3 that is production-ready. You can find it here: https://tillsanders.github.io/esm-itter/setup.html

Leaving this here for others looking for a solution to this.
