### ISSUE TITLE
Question: difference between this lib and browserify/events? 

### ISSUE THREAD

**Issue by jay-jlm** [primus/eventemitter3#236]
Hi,

Apart from the support for newer methods, it would be useful to know  - from someone who has is familiar with both implementations - more about the difference between these 2 libs and potential reasons to choose one over the other, since both seem to be equally popular on npm.

**Comment by lpinca** [comment]
`events` is a 1:1 copy of the built-in Node.js module. `eventemitter3` has some differences listed in the README and should be a little faster. I think that's all.

**Comment by jay-jlm** [comment]
@brunobertolini

**Comment by lpinca** [comment]
I'm closing this as answered. Discussion can continue if needed.
