### ISSUE TITLE
Consider to execute event listeners async?

### ISSUE THREAD

**Issue by yuanhongboo** [primus/eventemitter3#239]
Wondering why not execute event listeners async？In some scene, it may block the main process.

https://github.com/primus/eventemitter3/blob/3f61c9fdddd77fa0a3567b8827b46d13eaae2cb3/index.js#L166-L216

**Comment by lpinca** [comment]
> Wondering why not execute event listeners async？In some scene, it may block the main process.

That is ok, it is not common to add a lot of listeners for the same event and it is not a computationally intensive task unless the listeners handle the event with a synchronous computationally intensive task themself. Also the `EventEmitter` is designed to work synchronously. When an event is emitted, registered listeners should be called immediately, you don't want other things to happen before the event is handled. For example, think about an error event. If the listener is called asynchronously, the error context might have already changed.
