### ISSUE TITLE
Remove by context

### ISSUE THREAD

**Issue by drkibitz** [primus/eventemitter3#24]
If we can add listeners by context we should be able to remove by them as well.

This was brought up by this issue:
https://github.com/GoodBoyDigital/pixi.js/pull/1693.

Here is an example of how my lib originally based on Backbone.Events accomplishes this:
https://github.com/drkibitz/qi-events/blob/master/src/index.js#L153-L181
It is also unit tested:
https://github.com/drkibitz/qi-events/blob/master/test/unit/Events.test.js#L202-L239

For me this is a fundamental problem with the ee3 api, and would like to get this in. I am will to contribute and create a PR if needed, thanks.

**Comment by 3rd-Eden** [comment]
Big :+1: on this. Totally forgot about this thanks for the suggestion!

**Comment by drkibitz** [comment]
@3rd-Eden 
Wow that was some fast work, thanks a lot for the quick response!

Pinging @krzysztof-o  and @englercj for their info as well.

**Comment by englercj** [comment]
Hot damn that was fast, this solves a sticky issue for us when it is released.

**Comment by 3rd-Eden** [comment]
Will be in the `1.0.0` release that goes out today.
