### ISSUE TITLE
Can't import eventemitter3

### ISSUE THREAD

**Issue by griffi-gh** [primus/eventemitter3#245]
`import * as EventEmitter from './lib/eventemitter3.min.js';`
returns an empty Symbol object

`import EventEmitter from './lib/eventemitter3.min.js';`
doesn't work, throws a `export 'default' was not found` error

**Comment by sodapopzs** [comment]
I have the same issue. Any help appreciated.

**Comment by sodapopzs** [comment]
@griffi-gh  , I see you have closed this issue, but Idont see any updates to the code or any comments. Can you please explain how to resolve?

**Comment by griffi-gh** [comment]
@sodapopzs I just used esm.run, everything from that cdn works as es6 module flawlessly

**Comment by griffi-gh** [comment]
@sodapopzs I just used esm.run, everything from that cdn works as es6 module flawlessly.
