### ISSUE TITLE
help

### ISSUE THREAD

**Issue by a314949730** [primus/eventemitter3#247]
![image](https://user-images.githubusercontent.com/13251658/162567444-c17c2568-97cd-46c0-8753-0913a394f3a3.png)
![image](https://user-images.githubusercontent.com/13251658/162567452-595cf6ff-00d5-4fe7-bb12-a0eb2e850509.png)
Chromium: 70.0.3538.25

**Comment by lpinca** [comment]
Public class fields are not supported on Chrome 70. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields.
