### ISSUE TITLE
Plugin status » is deprecated?

### ISSUE THREAD

**Issue by jufemaiz** [primus/eventemitter3#249]
Hi all, just wanting to raise a question – is this plugin still supported or should it be classified as deprecated? (Noting last update is over 2 yrs ago)

**Comment by lpinca** [comment]
This module is still supported. It is "complete". Some of the new added feature of the Node.js `EventEmitter` are missing but I'm not sure we want to have them in `eventemitter3`. Feel free to open a PR to document the missing features.

**Comment by jufemaiz** [comment]
Thanks for the confirmation @lpinca!
