### ISSUE TITLE
The troublesome question about the emit function.

### ISSUE THREAD

**Issue by am0622** [primus/eventemitter3#250]
Why do you have the above block in the emit function instead of just using the bottom block? It seems to me that the bottom block completely contains the above.
![image](https://user-images.githubusercontent.com/49755350/200984319-d9743b0e-b4de-41a8-8888-6c031e38d46d.png)

**Comment by lpinca** [comment]
> Why do you have the above block in the emit function instead of just using the bottom block?

For performance reasons.

**Comment by am0622** [comment]
Why does this improve performance? I want to know how it works.
