### ISSUE TITLE
ESM support

### ISSUE THREAD

**Issue by unional** [primus/eventemitter3#251]
Is there any plan to update and support ESM?

There was a closed issue in the past #235, but that's old and is about adding `module: '...'`.

It would be great to support proper ESM:

```js
{
  "type": "module",
  "exports": {
    "import": "./esm/index.js",
     "require": "./cjs/index.js" // if supporting both ESM and cjs
   }
}
```

**Comment by tillsanders** [comment]
I created a native ESM-version of EventEmitter3 that is production-ready. You can find it here: https://tillsanders.github.io/esm-itter/setup.html
