### ISSUE TITLE
CDN missing

### ISSUE THREAD

**Issue by kblizeck** [primus/eventemitter3#253]
Looks like `https://unpkg.com/eventemitter3@latest/umd/eventemitter3.min.js` no longer exists? It redirects to `https://unpkg.com/eventemitter3@5.0.0/umd/eventemitter3.min.js` with the error `Cannot find "/umd/eventemitter3.min.js" in eventemitter3@5.0.0`

A Shopify theme we're using references the CDN - is there any way you can republish or provide a different link?
![Screen Shot 2022-11-28 at 6 07 38 PM](https://user-images.githubusercontent.com/9886123/204413483-437a6b6c-cf68-4f71-bff6-91f183edf778.png)

**Comment by lpinca** [comment]
See https://github.com/primus/eventemitter3/releases/tag/5.0.0
