### ISSUE TITLE
Requested module does not provide export named 'default' in vite

### ISSUE THREAD

**Issue by chua1989** [primus/eventemitter3#261]
in vite development server , when node_modules contains uncompiled source code，got error

index.mjs?v=73fd6c6e:1 Uncaught SyntaxError: The requested module '/node_modules/eventemitter3/index.js?v=73fd6c6e' does not provide an export named 'default' (at index.mjs?v=73fd6c6e:1:8)

![image](https://github.com/primus/eventemitter3/assets/17613057/3a97ac15-b34c-462d-b871-28fd35f5de20)

**Comment by lpinca** [comment]
In the browser you need to use the module under the `dist` folder (`eventemitter3.esm.js`). This is not an `eventemitter3` issue.

**Comment by chua1989** [comment]
@lpinca Thank you, now I know how to solve this problem, but I feel that the path of exports should be replaced by the files in dist
![image](https://github.com/primus/eventemitter3/assets/17613057/2c606850-c842-4f9b-a674-214caae7fc0b)

**Comment by lpinca** [comment]
> but I feel that the path of exports should be replaced by the files in dist.

No, those are for Node.js and for environments that reads `package.json`.

**Comment by lpinca** [comment]
I'm closing this as answered.

**Comment by sebbean** [comment]
i'm having this issue with electron vite 

loading the obs-websocket-js package 

<img width="1080" alt="image" src="https://github.com/user-attachments/assets/c3a19ee7-2c54-45f6-86b7-45af25b46b24">
