### ISSUE TITLE
`off` behaves differently than nodejs

### ISSUE THREAD

**Issue by uinz** [primus/eventemitter3#267]
#262 mentioned that the on method is consistent with nodejs, but I found that the off method is inconsistent with nodejs.

```json
{ "eventemitter3": "5.0.1" }
```

```ts
const ee = new EventEmitter()

ee.on('x', console.log)
ee.on('x', console.log)

ee.emit('x', 1) // print 1 twice

ee.off('x', console.log)


ee.emit('x', 1)
// expect: should print 1 once
// actual: no print
```

**Comment by lpinca** [comment]
See 

> - The `removeListener` method removes all matching listeners, not only the first.

`off` is an alias for `removeListener`.
