### ISSUE TITLE
Cannot read property 'prototype' of undefined error

### ISSUE THREAD

**Issue by jcrugzz** [primus/eventemitter3#29]
https://github.com/nodejitsu/node-http-proxy/issues/809

Haven't looked at why this happened but its a good thing version was pinned and you guys bumped to `1.0.0` :). People only ran into this issue because they were on an old version of `http-proxy`.

**Comment by jcrugzz** [comment]
Ah its because there is no longer a require('eventemitter3').EventEmitter

**Comment by 3rd-Eden** [comment]
Yes, root cause of that issue was because of `*` in the dependencies. Anyways, I'm add some release notes stating the breaking changes ;p
