### ISSUE TITLE
Error: Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by dhoko** [primus/eventemitter3#30]
```js
module.exports = EventEmitter;
```

It doesn't work, module is undefined. 

Patch:

```js
//
// Expose the module.
//
(module || {}).exports = EventEmitter;
```

**Comment by 3rd-Eden** [comment]
It works, as it was designed to be used in commonjs environment such as Node.js, IO.js, Browserify, React-native etc.

**Comment by dhoko** [comment]
And if you don't ?

**Comment by dhoko** [comment]
Sorry didn't see #22 it's sad to have to use browserify :/

**Comment by jcrugzz** [comment]
@dhoko we have found build systems like `browserify` and `webpack` to be more ideal for managing dependencies than just vendoring files in a project. You don't have to adopt the same pattern but we feel strongly enough about it that its encouraged in this manner. Nothing is perfect but having a front end application where you can easily install all your dependencies without copy and paste is incredible. Don't knock it until you try it ;).

**Comment by dhoko** [comment]
@jcrugzz I did use browserify for one year with many apps :) (last year). Today I'm working with another app and I don't want and need to use browserify or webpack.
