### ISSUE TITLE
Assumes window.module is there

### ISSUE THREAD

**Issue by renedx** [primus/eventemitter3#36]
This module in browser assumes the `window.module` is defined, but it isn't in our case. We don't use any fancy require systems but like to use this for our events (because, ofcourse!). 

Would it be a good idea to check for `module` to exist. Like most node/browser modules do? Or more preferably force people into a certain workflow? 

I'd like to know before even thinking of creating a pull :)

**Comment by renedx** [comment]
Ah ;)
https://github.com/primus/eventemitter3/issues/30#issuecomment-95678974

**Comment by renedx** [comment]
The reason I've ran into this problem (https://github.com/primus/eventemitter3/issues/30#issuecomment-95678974, https://github.com/primus/eventemitter3/issues/22#issuecomment-84005167) is because other modules check for `module.exports` to be there. So whenever I define it, other modules think I'm running it in node env. (`Uncaught TypeError: require is not a function`). I understand the statement, maybe worth a revaluation based on new information? ;)

**Comment by 3rd-Eden** [comment]
OK.

**Comment by 3rd-Eden** [comment]
THERE YOU GO, HAPPY NOW? :P

**Comment by renedx** [comment]
YES VEYR HAPPY :+1:

**Comment by 3rd-Eden** [comment]
![NICE](https://i37.photobucket.com/albums/e69/xrmaddness/VeryNice-1.gif)
