### ISSUE TITLE
Detailed comparison to eventemitter2

### ISSUE THREAD

**Issue by ghostsquad** [primus/eventemitter3#42]
Lightweight and fast are good, but if it doesn't do what I want, I can't use this. Can you do a simple "comparison" chart for eventemitter2 and eventemitter?

Currently, I'm looking for wildcard support, which seems is not supported.

**Comment by jo-asakura** [comment]
:+1: Yep, comparison chart would be nice.

**Comment by 3rd-Eden** [comment]
The README already states:

> The module is API compatible with the EventEmitter that ships by default with Node.js

So everything that EE2 adds on top is not supported.

**Comment by ghostsquad** [comment]
@3rd-Eden so, EE3 is just a faster EE. No additional features besides the bullet points at the top of the readme. Gotcha. Thanks!
