### ISSUE TITLE
confusing state of the npm package compared to package.json

### ISSUE THREAD

**Issue by getify** [primus/eventemitter3#47]
It seems strange/unexpected to me that I can install this package via npm, and even run `npm install` inside it to get all the dev-dependencies, but because `test.js` is [npm ignored](/primus/eventemitter3/issues/15) running the typical `npm test` fails.

Would you consider perhaps having `npm install` somehow pull down `test.js` (and any other necessary files) from github, or at a minimum throwing a warning that it's missing and that `npm test` will thus not run?

Or perhaps the `package.json` distributed via npm itself should be stripped of all that non-relevant stuff that the npm package itself will never be able to use?

**Comment by jcrugzz** [comment]
Unfortunately this is just the nature of `npm`. There is no clean way to do this but I'm sure @3rd-Eden is open to suggestions. The idea is for the `npm` installed version to be used and not looked at and if you wanted to run tests and all that jazz you'd clone the repo. This is more convention than prescriptive but thats the background on why the `test.js` would be included, no extra baggage when `npm install`ing an app.

**Comment by getify** [comment]
i haven't experienced the convention of `npm install && npm test` failing... but ok. whatevs. I think it should be more clearly documented what to expect.

**Comment by jcrugzz** [comment]
@getify Sure, that sounds great. Definitely open for a PR here :+1:

**Comment by lpinca** [comment]
This is my fault, I added `test.js` to `.npmignore`, see https://github.com/primus/eventemitter3/commit/997b58b4cbf428f6a816e19838f958ad7691a6a1.

I always do this to keep the package as small as possible and only include the minimum necessary. I'm not alone here, a lot of packages do this.

In this case there is only one test file and it is very small so I'm ok with shipping it along with the package.

**Comment by 3rd-Eden** [comment]
Things like test don't really belong in an installation. When you buy adobe photoshop and download their installer they don't ship you their complete test suite either. Same thing applies to all software packages. This actually a quite common and frequently requested thing by consumers as they want the installation to be a small as possible.

We could make it clear in the readme that if you want to run the test suite, you need to checkout the repository. I have no problem with that.

**Comment by alexindigo** [comment]
@getify Another option would be to submit PR to https://github.com/npm/npm to add something like `npm install --from-source` to perform git clone instead of untarring things from npm registry. :)
