### ISSUE TITLE
"newListener" event not supported?

### ISSUE THREAD

**Issue by frozeman** [primus/eventemitter3#50]
[This API](https://nodejs.org/api/events.html#events_event_newlistener) doesn't seem to be supported, why?

**Comment by lpinca** [comment]
From the documentation:
> The newListener event is removed as the use-cases for this functionality are really just edge cases.

**Comment by frozeman** [comment]
Argh!

How you would otherwise know if an event was added or removed? Thats the main tool to act invents being added IMO

**Comment by lpinca** [comment]
I guess it depends on the use case but the `listeners` method can be used:
```js
ee.listeners('foo', true);
// => `true` if there are listeners for the `foo` event, `false` otherwise.

ee.listeners('foo').includes(fn);
// => `true` if `fn` is a listener of the`foo` event, `false` otherwise.
```

**Comment by frozeman** [comment]
Sure, but if i'm waiting for a specific event to be added, than i would need to run this in a interval.

I switched to nodes default eventEmitter. Thanks anyway.

**Comment by lpinca** [comment]
Ok, yes in that case the `newListener` event makes sense. It shouldn't be hard to support this but I'm not sure if we want to add the feature.

**Comment by bjbrewster** [comment]
Here is a simple use case for supporting a 'newListener' event.  I personally do not think tit would be hard to support this event as it can be very useful. 

I have a client that receives updates from the server via a WebSocket that modifies a state object and then emits an 'update' event.  When a subscriber subscribes to the 'update' event, I would like my client to send it the current state object, and not wait until the next server message arrives that could be many minutes.

To get around this, I either have to:
- update my subscriber to call `client.getData()` before (or after?) it subscribes to the 'update' event
- change my Client class that extends EE to override the 'on' method  to send the latest data to the subscriber if event is 'update'

Is this a fringe case?  I'd rather EE have a newListener event so my Client's ctor can just:
```
this.on('newListener', (event, listener) => {
  if (event === 'update') listener(this.data)
})
```

**Comment by lpinca** [comment]
> - update my subscriber to call client.getData() before (or after?) it subscribes to the 'update' event

That seems reasonable to me. If I understand correctly, that's what you would do in the `newListener` listener anyway. So why not calling the `update` listener manually, one time, before adding it as a listener of the `update` event?

> Maybe someone can fork your project with this feature and call it EventEmitter4 - "ours is faster than Node and has 'newListener' support!!!" lolz

FYI there is already and EventEmitter4 so it could be EventEmitter5 and that someone could be you 😄.

**Comment by bjbrewster** [comment]
Lol, I created my first package EventEmitter5.  It was surprisingly easy. :)

The description is "For anyone thinking of creating an EventEmitter5 - no,
just no."

**Comment by banacorn** [comment]
I think this claim from the README should be dropped then
```Markdown 
It's a drop in replacement for existing EventEmitters
```
because this package is simply **NOT** a drop in replacement for existing EventEmitters
