### ISSUE TITLE
ES6 class extends

### ISSUE THREAD

**Issue by pietrovismara** [primus/eventemitter3#57]
Hi, using systemjs and es6 classes i tried to make this with my class:
```
import {EventEmitter} from 'eventemitter3';

export class Fetch extends EventEmitter {
    // code here....
}
```
But i got this error in console:
`Error: TypeError: Super expression must either be null or a function, not object(…)`

Is it possibile that eventemitter3 is not compatible with es6 classes?

**Comment by pietrovismara** [comment]
Sorry for the issue, it has been sufficient to change the import statement in this way:
`import EventEmitter from 'eventemitter3 ` to make it works.

**Comment by zpalexander** [comment]
Thanks for opening this issue! I had the same problem with the syntax: `import * as EventEmitter from 'eventemitter3'`
