### ISSUE TITLE
Allow passing context through options, not only through methods

### ISSUE THREAD

**Issue by tunnckoCore** [primus/eventemitter3#58]
Use case is simple. For example, we have App which needs emitting and emit events on every method.

``` js
var util = require('util')
var Emitter = require('eventemitter3')

function App (options) {
  if (!(this instanceof App)) {
    return new App(options)
  }
  Emitter.call(this)
  this.options = options || {}
  this.cache = {}
}

util.inherits(App, Emitter)

App.prototype.set = function set (key, value) {
  this.emit('set', key, value)
  this.cache[key] = value
  return this
}

App.prototype.del = function del (key) {
  this.emit('del', key)
  if (!key) {
    this.cache = {}
    return this
  }
  delete this.cache[key]
  return this
}

App.prototype.get = function get (key) {
  this.emit('get', key)
  return this.cache[key]
}

var app = new App()
app
  .on('set', fn, {foo: 'bar'})
  .on('get', fn, {foo: 'bar'})
  .on('del', fn, {foo: 'bar'})
```

Feature that this package add - allow passing context to on/off/once methods, but this does not solves the problem if you want to pass same context to each listener.
Maybe this isn't the best example, but I'm using event emitter (not exactly this package, in general) to emit different type of hooks - say, before/beforeEach/after/afterEach, and I need to pass same context to them. Then when users want to listen to some hook they just add `.on('beforeEach', fn)`, they can't add context to them - okey, they can, because if they can pass context to options, so they can pass to each listeners, but this would not be pretty and so useful and usable.

One way to do this would be to not inherit emitter directly, but write it to some property, then emit from it. But this also adds the need to create all of the listener methods (on/off/once) to allow your users to listen to that events. For example

``` js
function App (options) {
  if (!(this instanceof App)) {
    return new App(options)
  }
  this.emitter = new Emitter()
}
App.prototype.set = function set (key, value) {
  this.emitter.emit('set', key, value)
}
App.prototype.on = function (name, fn) {
  this.emitter.on(name, fn.bind(this.options.context))
  return this.emitter
}
```

But this leads to more unnecessary code that can be simpler if emitter can accept context through options. All this logic and stuff would be handled internally without the headaches. And this is easy to be implemented.

If this is implemented, things would look like that

``` js
var util = require('util')
var Emitter = require('eventemitter3')

function App (options) {
  if (!(this instanceof App)) {
    return new App(options)
  }
  Emitter.call(this, options)
  this.cache = {}
}

util.inherits(App, Emitter)

App.prototype.set = function set (key, value) {
  this.emit('set', key, value)
  this.cache[key] = value
  return this
}

App.prototype.del = function del (key) {
  this.emit('del', key)
  if (!key) {
    this.cache = {}
    return this
  }
  delete this.cache[key]
  return this
}

App.prototype.get = function get (key) {
  this.emit('get', key)
  return this.cache[key]
}

var app = new App({context: {foo: 'bar'}})
app
  .on('set', fn)
  .on('get', fn)
  .on('del', fn)
```

and all of the listeners would have `{foo: 'bar'}` context.

For more useful example you can see [async-control](https://github.com/hybridables/async-control)'s test.js, run it and look for `after all` output. Users can't pass context to each hook, or at least it's not their job, and that's not the logic. They may want to use and modify this context in the hooks, so they can manually pass to every listener method (on/off/once).

Hope understand it. I was about to publish one more emitter which do the job that way, and it's not with browser in mind and it's not compatible with node api. (and it's not needed to be, in my case). But also this package is pretty fast and we need speed.

**Comment by tunnckoCore** [comment]
Or I can it in that way, which is the ugly way:

```js
var Emitter = require('eventemitter3')

function FooEmitter (options) {
  if (!(this instanceof FooEmitter)) {
    return new FooEmitter(options)
  }
  this.options = options || {}
  this.emitter = new Emitter()
}

FooEmitter.prototype.on = function on (name, fn, context) {
  context = context ? extend(this.options.context, context) : this.options.context
  this.options.context = context || this
  this.emitter.on(name, fn, this.options.context)
  return this
}

FooEmitter.prototype.once = function once (name, fn, context) {
  context = context ? extend(this.options.context, context) : this.options.context
  this.options.context = context || this
  this.emitter.once(name, fn, this.options.context)
  return this
}

FooEmitter.prototype.off = function off (name, fn, context) {
  context = context ? extend(this.options.context, context) : this.options.context
  this.options.context = context || this
  this.emitter.once(name, fn, this.options.context)
  return this
}

FooEmitter.prototype.emit = function emit () {
  this.emitter.emit.apply(null, arguments)
 return this
}

module.exports = new FooEmitter()
module.exports.FooEmitter = FooEmitter
```

**Comment by lpinca** [comment]
What about this:
```js
'use strict';

const EE = require('eventemitter3');
const assert = require('assert');
const util = require('util');

function MyEmitter(opts) {
  this.context = opts.context;
}

util.inherits(MyEmitter, EE);

['on', 'once'].forEach(method => {
  MyEmitter.prototype[method] = function () {
    const args = Array.prototype.slice(arguments);
    return EE.prototype[method].apply(this, args.concat(this.context));
  };
});

const emitter = new MyEmitter({
  context: { foo: 'bar' }
});

emitter.on('event', function evt(data) {
  assert.deepStrictEqual(this, { foo: 'bar' });
  assert.strictEqual(data, 'baz');
});

emitter.emit('event', 'baz');
```
You only have to override the required methods, and you can do that in a loop.

**Comment by tunnckoCore** [comment]
Exactly, make sense and it's is always possible to do it in some way. It's possible, as I created it in above example, but it's not so elegance and worth nothing. I also think that it won't cost speed.

I created unopinionated and thin wrapper called http://npm.im/compose-emitter to do the job as we want it and it's also not limited to some exact emitter, you can pass emitter through options.

So thanks, we can close if you don't want to add that feature.

**Comment by lpinca** [comment]
I keep this open to make other people weigh in.

**Comment by lpinca** [comment]
Closing this, please comment or reopen if needed.
