### ISSUE TITLE
Extending EventEmitter in the coffeescript class

### ISSUE THREAD

**Issue by kmaraz** [primus/eventemitter3#59]
I'm trying to extend my coffeescript class with EventEmitter, but only accessible property is `_events`.
No other methods are available after extending this object.

Here is my code which is working:

`EventEmitter = require('eventemitter3')

module.exports = (ngModule) ->
    item = null

    Store = new EventEmitter()
    _.extend Store,
      getItem: -> item

    return Store`

And this is what I'm trying to accomplish:

`class Store extends EventEmitter

      @item = null

      getItem: =>
        @item

    return new Store()`

It doesn't have properties like `emit`, `on`, `off` etc., Just `_events`.

**Comment by lpinca** [comment]
This works fine:

```coffee
EE = require 'eventemitter3'

class MyEmitter extends EE
  constructor: (name) -> @name = name
  getName: -> @name

ee = new MyEmitter 'foo'

ee.on 'event', (data) -> console.log data
ee.emit 'event', 'hello'
```

**Comment by 3rd-Eden** [comment]
Closing as this is in no way a limitation or a bug in EE3.
