### ISSUE TITLE
removeListener function removes all subscriptions for a given listener and eventName

### ISSUE THREAD

**Issue by chintan-solanki** [primus/eventemitter3#63]
As per Nodejs EventEmitter documentation for removeListener function: 

> removeListener will remove, at most, one instance of a listener from the listener array. If any single listener has been added multiple times to the listener array for the specified eventName, then removeListener must be called multiple times to remove each instance.

eventEmitter3 removeListener implementation however seems to be removing all the subscriptions for a given eventName and listener function. Following is a sample code to reproduce the issue.

```js
var emitter = new window.EventEmitter();
var fn = function(){ alert("called");}

//add fn listener twice for event1
emitter.on("event1", fn);
emitter.on("event1", fn);

//try removing one listener
emitter.removeListener("event1",fn);

//expected: fn should get called once
//actual: fn doesn't get called
emitter.emit("event1");
```

**Comment by lpinca** [comment]
Yes, this is expected, that's how it is implemented in eventemitter3.

**Comment by chintan-solanki** [comment]
I see. Interesting. This is a deviation from the behavior documented on nodejs site [here](https://nodejs.org/api/events.html#events_emitter_removelistener_eventname_listener) and implemented by eventemitter2 library.

**Comment by lpinca** [comment]
Yes, you can even remove all listeners of a given event if you don't pass a function.

```js
ee.removeListner('event');
```

is the equivalent to

```js
ee.removeAllListeners('event');
```

**Comment by chintan-solanki** [comment]
Good to know that. Thanks. 

I think the point I am trying to make here is that, although it's a rare edge case,technically it's not a 100% 'drop in replacement for existing EventEmitters' as it does modify an existing behavior :)

**Comment by lpinca** [comment]
You are correct, but It has been like this as long as I can remember.
Maybe it makes sense to document this deviation.

**Comment by chintan-solanki** [comment]
I agree.

**Comment by lpinca** [comment]
Want to send a pr?

**Comment by chintan-solanki** [comment]
Sorry for the delay. Thanks for the closure.

**Comment by lpinca** [comment]
No problem.
