### ISSUE TITLE
Add TypeScript typings

### ISSUE THREAD

**Issue by Stubb0rn** [primus/eventemitter3#67]
I would like to see typescript typing information included into npm package. That would make using this library a lot easier in typescript projects. Currently there exists external [type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/cc3d223a946f661eff871787edeb0fcb8f0db156/eventemitter3) for this package, but it is out of date and seems to be incorrect. Of course I could contribute to that type definition, but first I would like to ask if package maintainers might be interested in including type definition in package itself. It would be the cleanest and most convenient way of handling typings for package users.
I would be happy to create PR with necessary changes if this is something package maintainers are interested in.

**Comment by lpinca** [comment]
I'm ok with this but this is something that should come from the community as we are not TypeScript users.

**Comment by 3rd-Eden** [comment]
+1 but it will not be maintained by us. But the EE interface it self should be rather stable.

**Comment by roblav96** [comment]
@lpinca Typescript is becoming very prominent; especially with ng2 on its way. Providing declarations should be just as important as providing a `bower` method. Please consider this 🍰

**Comment by lpinca** [comment]
@roblav96 sure, PR's are welcome :)

**Comment by lpinca** [comment]
Added in 2.0.2.
