### ISSUE TITLE
emitter.on with the callback being undefined causes a later crash

### ISSUE THREAD

**Issue by ThisIsMissEm** [primus/eventemitter3#78]
If I'm refactoring code, and I accidentally comment out an event handler, e.g., say I've:

```js

// const handleFoo = () => { /* ... */ }

myEmitter.on('foo', handleFoo);
```

Then later when I call:

```js
myEmitter.on('foo', () => { console.log('on foo'); });
```

Then that call will fail with an error of:

```
this._events[evt].push is not a function
```

The simple fix would be to add a bail out / error in `EventEmitter.prototype.on` that checks that the function it's going to add as a callback is actually a function.

**Comment by lpinca** [comment]
Yeah, the `EventEmitter` that ships with Node.js has that check, but I'm not sure if it's worth adding here. Using a falsy/non-function listener is obviously a programmer error.

The less code the better as this lib was made to be used in the browser.

**Comment by ThisIsMissEm** [comment]
@lpinca right, but without that error being raised, you can easily encounter this as a developer when refactoring, and the error that it creates is really confusing to try and resolve; Perhaps make it only if `process.env.NODE_ENV !== 'production'`

**Comment by eysi09** [comment]
I agree with @ThisIsMissEm, just spent a couple of hours debugging the exact the same thing. I have two components that listen to the same event on different screens of a React Native app and re-named the event handler on the former without updating the `emitter.on` params. However, it's not until I navigate to the second screen and do some stuff that causes the event emission that the handler for the first screen fails but the stack trace points to where I initialise the handler on the second screen.

**Comment by ggarek** [comment]
> The less code the better as this lib was made to be used in the browser.
