### ISSUE TITLE
CDN link

### ISSUE THREAD

**Issue by roccomuso** [primus/eventemitter3#80]
Is it worth adding a CDN link to the README?

**Comment by lpinca** [comment]
Like https://unpkg.com/ ?

**Comment by 3rd-Eden** [comment]
A CDN would be impossible, as we would need to host a primus+{every available transport and parser combination}.

**Comment by lpinca** [comment]
Arnout this is EE3 :)

**Comment by 3rd-Eden** [comment]
I'm an idiot.

**Comment by roccomuso** [comment]
Like [cdnjs.com](https://cdnjs.com)

**Comment by lpinca** [comment]
I didn't even know that it was there. I have no problem adding a link in the README.
Anyway I noticed that there isn't a UMD wrapper.

**Comment by lpinca** [comment]
Closing this, please open a PR if you think it's worth adding a CDN link in the README.
