### ISSUE TITLE
Browserified Bundle name not consistent

### ISSUE THREAD

**Issue by roccomuso** [primus/eventemitter3#81]
https://wzrd.in/standalone/eventemitter3@latest
The browserified bundle actually doesn't seems to export that function name properly.

This works: `var a = new eventemitter3()`
this doesn't: `var a = new EventEmitter()`
neither: `var a = require('eventemitter3')` being a standalone module, no require is needed.

**Comment by lpinca** [comment]
I guess wzrd.in uses the package name as `--standalone` option for browserify. I think there isn't anything actionable from our side.
