### ISSUE TITLE
Remove component.json and bower.json

### ISSUE THREAD

**Issue by lpinca** [primus/eventemitter3#86]
I wonder if it makes sense to remove `component.json` and `bower.json` from the root of this repo. Component is no longer maintained and Bower recommends to use yarn + webpack.

Would this be too disruptive? Is the UMD build from unpkg.com CDN enough?

**Comment by 3rd-Eden** [comment]
Maybe, I don't really care because I don't use it :/ but we probably don't want to break legacy apps that still use component.json so that might just be a major bump somehow.

**Comment by lpinca** [comment]
Yeah same here. Maintaining those two files is actually not a big burden but I think they are useless these days. Cutting a new major version only for this doesn't make sense so maybe it's better to revisit later when there are other breaking changes (this will probably never happen 😄).
